
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import project.select;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CJ
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLgEmail = new javax.swing.JTextField();
        txtLgPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnLSignUp = new javax.swing.JButton();
        btnLFP = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtLgEmail.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtLgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 310, -1));

        txtLgPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtLgPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 310, -1));

        btnLogin.setBackground(new java.awt.Color(102, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 110, 30));

        btnLSignUp.setBackground(new java.awt.Color(102, 0, 0));
        btnLSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnLSignUp.setText("SignUp");
        btnLSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLSignUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnLSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 30));

        btnLFP.setBackground(new java.awt.Color(102, 0, 0));
        btnLFP.setForeground(new java.awt.Color(255, 255, 255));
        btnLFP.setText("ForgotPassword");
        btnLFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLFPActionPerformed(evt);
            }
        });
        jPanel2.add(btnLFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 30));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(204, 0, 0));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        int a = JOptionPane.showConfirmDialog(null, "Do you want ot close the application","select",JOptionPane.YES_NO_OPTION);
        if(a == 0)
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        int check = 0;
        
        String email = txtLgEmail.getText();
        String password = txtLgPassword.getText();
        
        if(email.equals("") || password.equals(""))
        {
            check = 1;
            JOptionPane.showMessageDialog(null, "every fields are reqired....");
        }
        else if(email.equals("nibm") && password.equals("admin"))
        {
            check = 1;
            setVisible(false);
            new adminHome().setVisible(true);
        }
        else
        {
            ResultSet rs = select.GetData("SELECT * FROM users WHERE email='"+email+"' AND password='"+password+"'");
            try {
                
                if(rs.next())
                {
                    check = 1;
                    if(rs.getString(7).equals(true))
                    {
                        setVisible(false);
                        new home().setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "wait for admin aprovel....");
                    }
                }
            } 
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(check == 0)
        {
            JOptionPane.showMessageDialog(null, "incorrect email or password...");
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLSignUpActionPerformed
        
        setVisible(false);
        new signup().setVisible(true);
        
    }//GEN-LAST:event_btnLSignUpActionPerformed

    private void btnLFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLFPActionPerformed
       
        setVisible(false);
         new forgotPassword().setVisible(true);
    }//GEN-LAST:event_btnLFPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLFP;
    private javax.swing.JButton btnLSignUp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtLgEmail;
    private javax.swing.JPasswordField txtLgPassword;
    // End of variables declaration//GEN-END:variables

    private void elseif() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
